---
# Variable configuration
- include_tasks: variables.yml

# Setup/install tasks
- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: build.yml
- include_tasks: initialize.yml

# TODO: - include_tasks: configure.yml

- name: Ensure Plantd Configure is started and enabled on boot.
  systemd:
    name: "{{ plantd_configure_daemon }}"
    state: "{{ plantd_configure_service_state }}"
    enabled: "{{ plantd_configure_service_enabled }}"
  tags: [ "plantd-configure" ]

# Configure Plantd Configure
#- import_tasks: databases.yml
#- import_tasks: users.yml
