---
# Variable configuration.
- name: Include OS-specific variables (Debian stable)
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian' and ansible_distribution_version != 'buster/sid'

- name: Include OS-specific variables (Debian testing)
  include_vars: "{{ ansible_distribution }}-10.yml"
  when: ansible_os_family == 'Debian' and ansible_distribution_version == 'buster/sid'

- name: Define plantd_configure_version
  set_fact:
    plantd_configure_version: "{{ __plantd_configure_version }}"
  when: plantd_configure_version is not defined

- name: Define plantd_configure_daemon
  set_fact:
    plantd_configure_daemon: "{{ __plantd_configure_daemon }}"
  when: plantd_configure_daemon is not defined

- name: Define __plantd_configure_srcdir
  set_fact:
    plantd_configure_srcdir: "{{ __plantd_configure_srcdir }}"
  when: plantd_configure_srcdir is not defined

- name: Define plantd_configure_packages
  set_fact:
    plantd_configure_packages: "{{ __plantd_configure_packages | list }}"
  when: plantd_configure_packages is not defined
